DROP TABLE IF EXISTS cronometer2_dailysummary;
CREATE TABLE cronometer2_dailysummary(
  Timestamp INT,
  Reported TEXT,
  Date TEXT,
  "Energy (kcal)" TEXT,
  "Alcohol (g)" TEXT,
  "Caffeine (mg)" TEXT,
  "Water (g)" TEXT,
  "B1 (Thiamine) (mg)" TEXT,
  "B2 (Riboflavin) (mg)" TEXT,
  "B3 (Niacin) (mg)" TEXT,
  "B5 (Pantothenic Acid) (mg)" TEXT,
  "B6 (Pyridoxine) (mg)" TEXT,
  "B12 (Cobalamin) (µg)" TEXT,
  "Folate (µg)" TEXT,
  "Vitamin A (µg)" TEXT,
  "Vitamin C (mg)" TEXT,
  "Vitamin D (IU)" TEXT,
  "Vitamin E (mg)" TEXT,
  "Vitamin K (µg)" TEXT,
  "Calcium (mg)" TEXT,
  "Copper (mg)" TEXT,
  "Iron (mg)" TEXT,
  "Magnesium (mg)" TEXT,
  "Manganese (mg)" TEXT,
  "Phosphorus (mg)" TEXT,
  "Potassium (mg)" TEXT,
  "Selenium (µg)" TEXT,
  "Sodium (mg)" TEXT,
  "Zinc (mg)" TEXT,
  "Carbs (g)" TEXT,
  "Fiber (g)" TEXT,
  "Starch (g)" TEXT,
  "Sugars (g)" TEXT,
  "Net Carbs (g)" TEXT,
  "Fat (g)" TEXT,
  "Cholesterol (mg)" TEXT,
  "Monounsaturated (g)" TEXT,
  "Polyunsaturated (g)" TEXT,
  "Saturated (g)" TEXT,
  "Trans-Fats (g)" TEXT,
  "Omega-3 (g)" TEXT,
  "Omega-6 (g)" TEXT,
  "Cystine (g)" TEXT,
  "Histidine (g)" TEXT,
  "Isoleucine (g)" TEXT,
  "Leucine (g)" TEXT,
  "Lysine (g)" TEXT,
  "Methionine (g)" TEXT,
  "Phenylalanine (g)" TEXT,
  "Protein (g)" TEXT,
  "Threonine (g)" TEXT,
  "Tryptophan (g)" TEXT,
  "Tyrosine (g)" TEXT,
  "Valine (g)" TEXT,
  Completed TEXT
);
DROP TABLE IF EXISTS "cronometer2_fasts";
CREATE TABLE IF NOT EXISTS "cronometer2_fasts"(
"Name" TEXT, "Start" TEXT, "End" TEXT, "Recurrence" TEXT,
 "Comments" TEXT);

DROP TABLE IF EXISTS cronometer2_servings;
CREATE TABLE cronometer2_servings(
  Timestamp INT,
  Reported TEXT,
  Day TEXT,
  "Group",
  "Food Name" TEXT,
  Amount TEXT,
  "Energy (kcal)" TEXT,
  "Alcohol (g)" TEXT,
  "Caffeine (mg)" TEXT,
  "Water (g)" TEXT,
  "B1 (Thiamine) (mg)" TEXT,
  "B2 (Riboflavin) (mg)" TEXT,
  "B3 (Niacin) (mg)" TEXT,
  "B5 (Pantothenic Acid) (mg)" TEXT,
  "B6 (Pyridoxine) (mg)" TEXT,
  "B12 (Cobalamin) (µg)" TEXT,
  "Folate (µg)" TEXT,
  "Vitamin A (µg)" TEXT,
  "Vitamin C (mg)" TEXT,
  "Vitamin D (IU)" TEXT,
  "Vitamin E (mg)" TEXT,
  "Vitamin K (µg)" TEXT,
  "Calcium (mg)" TEXT,
  "Copper (mg)" TEXT,
  "Iron (mg)" TEXT,
  "Magnesium (mg)" TEXT,
  "Manganese (mg)" TEXT,
  "Phosphorus (mg)" TEXT,
  "Potassium (mg)" TEXT,
  "Selenium (µg)" TEXT,
  "Sodium (mg)" TEXT,
  "Zinc (mg)" TEXT,
  "Carbs (g)" TEXT,
  "Fiber (g)" TEXT,
  "Starch (g)" TEXT,
  "Sugars (g)" TEXT,
  "Net Carbs (g)" TEXT,
  "Fat (g)" TEXT,
  "Cholesterol (mg)" TEXT,
  "Monounsaturated (g)" TEXT,
  "Polyunsaturated (g)" TEXT,
  "Saturated (g)" TEXT,
  "Trans-Fats (g)" TEXT,
  "Omega-3 (g)" TEXT,
  "Omega-6 (g)" TEXT,
  "Cystine (g)" TEXT,
  "Histidine (g)" TEXT,
  "Isoleucine (g)" TEXT,
  "Leucine (g)" TEXT,
  "Lysine (g)" TEXT,
  "Methionine (g)" TEXT,
  "Phenylalanine (g)" TEXT,
  "Protein (g)" TEXT,
  "Threonine (g)" TEXT,
  "Tryptophan (g)" TEXT,
  "Tyrosine (g)" TEXT,
  "Valine (g)" TEXT,
  Category TEXT
);
DROP TABLE IF EXISTS cronometer2_NOTES;
CREATE TABLE cronometer2_NOTES(
  Timestamp INT,
  Reported TEXT,
  Day TEXT,
  "Group",
  Note TEXT
);
DROP TABLE IF EXISTS cronometer2_EXERCISES;
CREATE TABLE cronometer2_EXERCISES(
  Day TEXT,
  Reported TEXT,
  "Group",
  Timestamp INT,
  Exercise TEXT,
  Minutes TEXT,
  "Calories Burned" TEXT
);
DROP TABLE IF EXISTS cronometer2_BIOMETRICS;
CREATE TABLE cronometer2_BIOMETRICS(
  Timestamp INT,
  Reported TEXT,
  Day TEXT,
  "Group",
  Metric TEXT,
  Unit TEXT,
  Amount TEXT
);
CREATE UNIQUE INDEX cronometer2_dailysummary_idx on cronometer2_dailysummary (timestamp, date);
